import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

export async function GET() {
  try {
    const supabase = await createClient()
    // 检查是否有 admin session
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    
    // 使用 service_role key 执行 SQL
    const { data, error } = await supabase.rpc('exec_sql', { 
      sql: `
        ALTER TABLE profiles ADD COLUMN IF NOT EXISTS membership_level TEXT DEFAULT 'regular';
        ALTER TABLE profiles ADD COLUMN IF NOT EXISTS gold_draws_remaining INTEGER DEFAULT 0;
        
        CREATE TABLE IF NOT EXISTS donations (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
          username TEXT NOT NULL,
          amount DECIMAL(10,2) NOT NULL,
          plan TEXT NOT NULL CHECK (plan IN ('gold', 'diamond')),
          status TEXT NOT NULL DEFAULT 'completed' CHECK (status IN ('pending', 'completed', 'cancelled')),
          created_at TIMESTAMPTZ DEFAULT NOW()
        );
        ALTER TABLE donations ENABLE ROW LEVEL SECURITY;
        
        CREATE TABLE IF NOT EXISTS lottery_records (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
          lottery_type TEXT NOT NULL CHECK (lottery_type IN ('ssq', 'dlt', 'fc3d', 'sg4d', 'toto')),
          numbers JSONB NOT NULL,
          ticket_numbers JSONB,
          created_at TIMESTAMPTZ DEFAULT NOW()
        );
        ALTER TABLE lottery_records ENABLE ROW LEVEL SECURITY;
        
        CREATE INDEX IF NOT EXISTS idx_donations_created ON donations(created_at DESC);
        CREATE INDEX IF NOT EXISTS idx_lottery_records_user ON lottery_records(user_id);
      `
    })
    
    if (error) return NextResponse.json({ error: error.message }, { status: 500 })
    return NextResponse.json({ success: true, data })
  } catch (e) {
    return NextResponse.json({ error: e.message }, { status: 500 })
  }
}
