-- ============================================================
-- 🎰 古道论坛 · 彩票模拟器 + 会员等级系统
-- 在 Supabase SQL Editor 运行此脚本
-- ============================================================

-- 1. profiles 表扩展：会员等级
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS membership_level TEXT DEFAULT 'regular';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS gold_draws_remaining INTEGER DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS membership_level TEXT DEFAULT 'regular';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS gold_draws_remaining INTEGER DEFAULT 0;

-- 2. 打赏记录表
CREATE TABLE IF NOT EXISTS donations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  username TEXT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  plan TEXT NOT NULL CHECK (plan IN ('gold', 'diamond')),
  status TEXT NOT NULL DEFAULT 'completed' CHECK (status IN ('pending', 'completed', 'cancelled')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE donations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can read donations" ON donations FOR SELECT USING (true);
CREATE POLICY "Admin can insert donation" ON donations FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- 3. 彩票摇奖记录表
CREATE TABLE IF NOT EXISTS lottery_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  lottery_type TEXT NOT NULL CHECK (lottery_type IN ('ssq', 'dlt', 'fc3d', 'sg4d', 'toto')),
  numbers JSONB NOT NULL,
  ticket_numbers JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE lottery_records ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own records" ON lottery_records FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Admin can view all" ON lottery_records FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Users can insert own records" ON lottery_records FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 4. 创建索引
CREATE INDEX IF NOT EXISTS idx_lottery_records_user ON lottery_records(user_id);
CREATE INDEX IF NOT EXISTS idx_lottery_records_type ON lottery_records(lottery_type);
CREATE INDEX IF NOT EXISTS idx_donations_created ON donations(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_donations_status ON donations(status);

-- 5. 设置浩哥为管理员+钻石会员
UPDATE profiles SET role = 'admin', membership_level = 'diamond' WHERE username = '浩哥' OR display_name = '浩哥';
